spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: create

logging:
  level:
    root: INFO
